# Generated by Django 4.2.1 on 2023-06-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=32)),
                ('order_id', models.PositiveIntegerField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_id', models.PositiveIntegerField()),
            ],
        ),
    ]
